First pass - Type errors
pyta-uoft/website pull request #57
Opened 2017-06-07 22:58 UTC by ostrokach

2017-06-11 20:40 UTC, david-yz-liu requested changes
Great work. I only left a few minor comments.

2017-06-11 20:40 UTC, david-yz-liu commented on index.md
> +In the following example, `add_fruit` modifies `fruit_basket` inplace and does not return anything. As a result, `new_fruit_basket` always gets the value `None`.
Use the term "mutate" rather than "modify," and don't use the term "inplace."

2017-06-11 20:40 UTC, david-yz-liu commented on index.md
> +You should either modify `add_fruit` to return a new list, or call `add_fruit` without assigning the return value to a variable.
Let's use the first-person voice for these examples: "We should either..."

2017-06-26 13:11 UTC, david-yz-liu approved these changes

2017-06-26 15:37 UTC, nigef commented on index.md
> +This error occurs when you use the membership test `a in b`, but the type of `b`
Please avoid using the word "you", here and in other instances.  I believe this has been mentioned before.
There are many ways a phrase could be reworded, for example, 
> This error occurs when the membership of `a` is tested in `b`, i.e.  `a in b`, but the type of `b` does not support membership tests.

2017-06-26 15:39 UTC, nigef commented on index.md
> +    or decrement a variable with ++ or --.~~~~
typo?

2017-06-26 15:40 UTC, nigef commented on index.md
> +We should either modify `add_fruit` to return a new list, or call `add_fruit` without assigning the return value to a variable.
Please reword to not use "we".

2017-07-02 15:00 UTC, merged